"""
Analytics & Supervisory Attention REST Endpoints for SAT-SA.
Supports CSE-level supervisory assessment, 8 capability dimensions, and evidence traceability.
Clean exception handling with structured HTTP responses.
"""

from fastapi import APIRouter, HTTPException
import json
import pandas as pd

from src.db.connection import get_db_connection
from src.analytics.scoring import calculate_supervisory_attention_scores
from src.analytics.outliers import detect_statistical_outliers
from src.analytics.similarity import detect_repetitive_investigations

router = APIRouter(prefix="/api/v1/analytics", tags=["Analytics"])


@router.post("/run")
def run_analytics_pipeline():
    """
    Triggers complete analytics pipeline calculation and updates supervisory scores.
    """
    conn = get_db_connection(read_only=False)
    try:
        results = calculate_supervisory_attention_scores(conn)
        return {
            "status": "success",
            "cses_assessed": len(results["cse_scores"]),
            "findings_generated": len(results["findings_df"]),
            "analysts_scored": len(results["analyst_scores"]),
            "tickets_scored": len(results["ticket_scores"]),
            "high_similarity_pairs_detected": len(results["high_similarity_pairs"])
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Analytics execution failed", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/overview")
def get_soc_overview():
    """
    Returns high-level SOC operational KPIs and CSE assessment metrics.
    """
    conn = get_db_connection(read_only=True)
    try:
        df_stats = conn.execute("""
            SELECT 
                (SELECT COUNT(*) FROM cses) AS total_cses,
                (SELECT COUNT(*) FROM assets) AS total_assets,
                (SELECT COUNT(*) FROM alerts) AS total_alerts,
                (SELECT COUNT(*) FROM tickets) AS total_tickets,
                (SELECT COUNT(*) FROM findings) AS total_findings,
                (SELECT COUNT(*) FROM supervisory_scores WHERE entity_type='cse' AND total_score >= 35) AS high_attention_cses
        """).df()

        if df_stats.empty:
            return {"status": "success", "kpis": {}}

        row = df_stats.iloc[0].to_dict()
        row["disclaimer"] = "Prototype Supervisory Attention Indicator — not an official NCIIPC risk score."
        return {
            "status": "success",
            "kpis": row
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve SOC overview KPIs", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/cses")
def get_cse_assessment_queue():
    """
    Returns prioritized queue of Critical Sector Entities (CSEs) ranked by Supervisory Attention Indicator.
    """
    conn = get_db_connection(read_only=False)
    try:
        results = calculate_supervisory_attention_scores(conn)
        df_cses = results["cse_scores"]
        df_findings = results["findings_df"]

        cses_list = df_cses.to_dict(orient="records") if not df_cses.empty else []
        findings_list = df_findings.to_dict(orient="records") if not df_findings.empty else []

        return {
            "status": "success",
            "disclaimer": "Prototype Supervisory Attention Indicator — not an official NCIIPC risk score.",
            "cses": cses_list,
            "findings": findings_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve CSE assessment queue", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/findings")
def get_evidence_findings(cse_id: str = None, dimension: str = None):
    """
    Returns structured evidence findings generated by the 8 capability dimensions engine.
    Filterable by cse_id or capability dimension.
    """
    conn = get_db_connection(read_only=True)
    try:
        query = "SELECT * FROM findings WHERE 1=1"
        params = []
        if cse_id:
            query += " AND cse_id = ?"
            params.append(cse_id)
        if dimension:
            query += " AND dimension = ?"
            params.append(dimension)

        df = conn.execute(query, params).df()
        findings_list = df.to_dict(orient="records") if not df.empty else []

        return {
            "status": "success",
            "count": len(findings_list),
            "findings": findings_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve findings", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/evidence/{finding_id}")
def trace_finding_evidence(finding_id: str):
    """
    Traces a structured finding to its source evidence database records (Alerts, Tickets, Notes, Shifts, Assets).
    """
    conn = get_db_connection(read_only=True)
    try:
        df_finding = conn.execute("SELECT * FROM findings WHERE finding_id = ?", [finding_id]).df()
        if df_finding.empty:
            raise HTTPException(status_code=404, detail=f"Finding with ID '{finding_id}' not found.")

        finding_row = df_finding.iloc[0].to_dict()
        source_type = finding_row["source_record_type"]
        evidence_ids = [e.strip() for e in finding_row["evidence_record_ids"].split(",") if e.strip()]

        records = []
        if evidence_ids:
            placeholders = ",".join(["?"] * len(evidence_ids))
            if source_type == "alert":
                records = conn.execute(f"SELECT * FROM alerts WHERE alert_id IN ({placeholders})", evidence_ids).df().to_dict(orient="records")
            elif source_type == "ticket":
                records = conn.execute(f"SELECT * FROM tickets WHERE ticket_id IN ({placeholders})", evidence_ids).df().to_dict(orient="records")
            elif source_type == "note":
                records = conn.execute(f"SELECT * FROM investigation_notes WHERE note_id IN ({placeholders})", evidence_ids).df().to_dict(orient="records")
            elif source_type == "shift":
                records = conn.execute(f"SELECT * FROM shift_logs WHERE log_id IN ({placeholders})", evidence_ids).df().to_dict(orient="records")

        return {
            "status": "success",
            "finding": finding_row,
            "evidence_records_count": len(records),
            "evidence_records": records
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to trace finding evidence", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/analysts")
def get_analyst_attention_queue():
    """
    Returns analyst-level supervisory attention scores and behavioral indicators.
    """
    conn = get_db_connection(read_only=False)
    try:
        results = calculate_supervisory_attention_scores(conn)
        df_analysts = results["analyst_scores"]
        analyst_list = df_analysts.to_dict(orient="records") if not df_analysts.empty else []

        return {
            "status": "success",
            "analysts": analyst_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve analyst attention queue", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/tickets")
def get_ticket_attention_queue():
    """
    Returns ticket-level supervisory attention queue and behavioral indicators.
    """
    conn = get_db_connection(read_only=False)
    try:
        results = calculate_supervisory_attention_scores(conn)
        df_tickets = results["ticket_scores"]
        ticket_list = df_tickets.to_dict(orient="records") if not df_tickets.empty else []

        return {
            "status": "success",
            "tickets": ticket_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve ticket attention queue", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/benchmarking")
def get_peer_benchmarking():
    """
    Returns peer cohort benchmarking statistical outliers (Z-Score & IQR analysis).
    """
    conn = get_db_connection(read_only=True)
    try:
        df_outliers = detect_statistical_outliers(conn)
        outliers_list = df_outliers.to_dict(orient="records") if not df_outliers.empty else []

        return {
            "status": "success",
            "peer_outliers": outliers_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to calculate peer benchmarking", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/similarity")
def get_repetitive_investigation_notes():
    """
    Returns high pairwise TF-IDF cosine similarity copy-paste note pairs.
    """
    conn = get_db_connection(read_only=True)
    try:
        results = detect_repetitive_investigations(conn)
        df_pairs = results["high_similarity_pairs"]
        pairs_list = df_pairs.to_dict(orient="records") if not df_pairs.empty else []

        return {
            "status": "success",
            "high_similarity_pairs_count": len(pairs_list),
            "pairs": pairs_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to run text similarity analysis", "message": str(e)}
        )
    finally:
        conn.close()


@router.get("/assets")
def get_asset_inventory(cse_id: str = None):
    """
    Returns CSE asset inventory and associated security alert telemetry.
    """
    conn = get_db_connection(read_only=True)
    try:
        query = "SELECT a.*, c.entity_name AS cse_name FROM assets a JOIN cses c ON a.cse_id = c.cse_id WHERE 1=1"
        params = []
        if cse_id:
            query += " AND a.cse_id = ?"
            params.append(cse_id)

        df_assets = conn.execute(query, params).df()
        assets_list = df_assets.to_dict(orient="records") if not df_assets.empty else []

        return {
            "status": "success",
            "count": len(assets_list),
            "assets": assets_list
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Failed to retrieve asset inventory", "message": str(e)}
        )
    finally:
        conn.close()
